Name: ProductionAyer
Type: FolderType
Children:
- Name: Hour_0
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_2
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_6
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_7
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_10
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_11
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_12
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_13
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_14
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_15
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_16
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_17
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_18
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_19
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_20
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_21
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_22
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_23
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_0
  Id: g=4f6a94cdd577461f84cdf236c23fa181
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_1
  Id: g=5989e82f6203400fa2bf4ea5528537d5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_2
  Id: g=ac20addda91b49d78cb8473ae8ef29bb
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_3
  Id: g=ac2e9409b99445759511ca2695b3186b
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_4
  Id: g=21f20bda18f242548a10a67328f0333a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_5
  Id: g=c63c663e370440f2b6159c296d9c36bb
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_6
  Id: g=00346c6511514d37adbe0a1ac63079fd
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_7
  Id: g=da9370ea37554cc08dd6cb129337006e
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_8
  Id: g=8c905fc876ac413bbcd11ef0be4b4aaa
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_9
  Id: g=94c89529ca834798a42fc8c82b41d00f
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_10
  Id: g=b5d0fd3290ff4a0aba5e57d7bb1bebba
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_11
  Id: g=c89204bc91ea4d34a7fbd3883fe4adb9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_12
  Id: g=58913876a0df422495335c9ff05e1708
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_13
  Id: g=7b8b65315c234bec96f522c8df7fdd99
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_14
  Id: g=542b349048a54989b8019eac607d535c
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_15
  Id: g=f833e22fa2bd42d5a3352aab6b9cb521
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_16
  Id: g=035dfa29f8e24ab5a51a2b94a71b795c
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_17
  Id: g=6d63ef28412f42448ff024b2764a45cb
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_18
  Id: g=43e3507e683b4cefbc6acccb27cca637
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_19
  Id: g=2a7e448617e84fb2928aa3b48fb9a2e8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_20
  Id: g=64bb11bbbaa540a8b390b6f1c8fc699b
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_21
  Id: g=2a648c2b2a2b4f908382afd5159b85b9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_22
  Id: g=e0952d62ba74430b9a77f725061a796b
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_23
  Id: g=69ca01529e084a3599a759865aa54e1a
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoPrimeroAyer
  Id: g=55f87ad35a8143d591fe808c11a93f2f
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoSegundoAyer
  Id: g=547bf8e214d048cdada181068b14c70f
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoTerceroAyer
  Id: g=12f2189408ad45d88ea44f6f050958bd
  Type: BaseDataVariableType
  DataType: Int32
