Name: Production
Type: FolderType
Children:
- Name: Hour_0
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_2
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_6
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_7
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_10
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_11
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_12
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_13
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_14
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_15
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_16
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_17
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_18
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_19
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_20
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_21
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_22
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_23
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_0
  Id: g=4191134989f89cea1c14caf8521cb7e1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_1
  Id: g=b141091be432f84d9eb68f1ba98bca7f
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_2
  Id: g=1d3375ca1d9150b697bd22b35e2d84f8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_3
  Id: g=4ea83b18e34828152484127640357416
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_4
  Id: g=158fe0a4d5f6eb147ece4c09ee63ae91
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_5
  Id: g=a1fea32a959e389f113ea4518635a991
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_6
  Id: g=3b03eca06bcda26a05af668ad8d9bb23
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_7
  Id: g=4ab14305b48a9cc19a729e7189e1d164
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_8
  Id: g=e3e6e60f56de7e5dca2ee465117b7460
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_9
  Id: g=409cbc68f587173a8cda14c81f6f541a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_10
  Id: g=7feae989ec63101047a4d364353c756b
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_11
  Id: g=9108a90618f59e80f920a733c40d24a3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_12
  Id: g=c4b4086afea25ef097e13dbc412ea718
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_13
  Id: g=7c49bc5fdd36b65c0caade00b19efd4f
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_14
  Id: g=c041ad3cd59aa197a9451b5f929ab379
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_15
  Id: g=7f6d5cd889d69b9a08d99d287e7add9e
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_16
  Id: g=402f377fd6ec6ad6df5f878af5960d7a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_17
  Id: g=e9f685d4320e01aa498fdd372b95165a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_18
  Id: g=a3a72821a0e8316b4ce302d501bf01c8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_19
  Id: g=60c6a5999b84ea5fcb0604fd472198e4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_20
  Id: g=d29c91d846252d2e13f1cdd639b33a78
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_21
  Id: g=2cef3e7dc7c6e8e9306df02f4dd7dc0b
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_22
  Id: g=e2858777ac1a4b9032980ed21024fe45
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_23
  Id: g=29d8d69c4ecc5baaa004879d9e1f538c
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoPrimero
  Id: g=13256b32df1934ae2a4dc41f4d5798e8
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoSegundo
  Id: g=adbdb47a37a78bbeeaf9c39f314d543e
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoTercero
  Id: g=3ce849c31b02c877d13a79021b40105f
  Type: BaseDataVariableType
  DataType: Int32
- Name: CellName
  Type: BaseDataVariableType
  DataType: String
  Value: "AU426 01"
