Name: Production
Type: FolderType
Children:
- Name: Hour_0
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_2
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_6
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_7
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_10
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_11
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_12
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_13
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_14
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_15
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_16
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_17
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_18
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_19
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_20
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_21
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_22
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_23
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_0
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_2
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_6
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_7
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_10
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_11
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_12
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_13
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_14
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_15
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_16
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_17
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_18
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_19
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_20
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_21
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_22
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_23
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoPrimero
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoSegundo
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoTercero
  Type: BaseDataVariableType
  DataType: Int32
- Name: CellName
  Type: BaseDataVariableType
  DataType: String
  Value: "AU426 01"
