Name: Production
Type: FolderType
Children:
- Name: Hour_0
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_1
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_2
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_5
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_6
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_7
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_9
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_10
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_11
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_12
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_13
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_14
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_15
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_16
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_17
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_18
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_19
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_20
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_21
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_22
  Type: BaseDataVariableType
  DataType: Int32
- Name: Hour_23
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_0
  Id: g=13ed20656a7045b9a10c3f9f62b87f62
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_1
  Id: g=e417ac4e97ed4bf088c00ed71dfa3cc4
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_2
  Id: g=cf522bea89ba460386342a425da8220c
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_3
  Id: g=94f7e3b92c7943e5adf3e03aeed3a5aa
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_4
  Id: g=733d080b30534d869221773dc2064bb3
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_5
  Id: g=3f6bbb815d53477eadfee5d125202130
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_6
  Id: g=ff2f725fc69b4965950e1a5f917e4b2a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_7
  Id: g=cb6024c66f8b4d2a82c7dfaf92ab3f2a
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_8
  Id: g=ff401d480a9147d38cfc3696d3ad1de8
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_9
  Id: g=ecab51eecf3e4d348f0e449016f5920c
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_10
  Id: g=86859e9d6b1d4344b6354ac930b54682
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_11
  Id: g=65e2248c4c35447eaa627cfa4d2305bf
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_12
  Id: g=b2dc375d1852426c935aa97bf59a7458
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_13
  Id: g=8b320420f226476e95de7e5a05efbc1d
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_14
  Id: g=373b0619c33b45e0a605c5b1881c17ce
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_15
  Id: g=a48a1ab37c37441db27560252cbd974f
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_16
  Id: g=a6e0a11f165945879ecabe4f912b6276
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_17
  Id: g=20d4a07d31ed46c8986fb41b81cd0990
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_18
  Id: g=6dfd50f4730a404cb4c0376ba9ed2b71
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_19
  Id: g=795d011ba0014775a83a2bbceed8665c
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_20
  Id: g=8807962214674e288d0987218bcdbb42
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_21
  Id: g=6b15aa1fa96248d1a77cb2aed0330887
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_22
  Id: g=ca367b9c80e24a9ab87785d658a95c32
  Type: BaseDataVariableType
  DataType: Int32
- Name: Count_23
  Id: g=b27ba830958d4163a6410db66fece1c6
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoPrimero
  Id: g=8b9c300894b240a68d33eceb5a2f7261
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoSegundo
  Id: g=f69f5502712a476f83048c345c41e533
  Type: BaseDataVariableType
  DataType: Int32
- Name: TurnoTercero
  Id: g=c6d619f4bcd94e46b9c2415b58d85800
  Type: BaseDataVariableType
  DataType: Int32
- Name: CellName
  Type: BaseDataVariableType
  DataType: String
  Value: "AU426 01"
